let songs = [
"Tim McGraw",
"Picture To Burn",
"Teardrops On My Guitar - Radio Single Remix",
"A Place in this World",
"Cold As You",
"The Outside",
"Tied Together with a Smile",
"Stay Beautiful",
"Should've Said No",
"Mary's Song (Oh My My My)",
"Our Song",
"I'm Only Me When I'm With You",
"Invisible",
"A Perfectly Good Heart",
"Teardrops on My Guitar - Pop Version",
"Mine - POP Mix",
"Sparks Fly",
"Back To December",
"Speak Now",
"Dear John",
"Mean",
"The Story Of Us",
"Never Grow Up",
"Enchanted",
"Better Than Revenge",
"Innocent",
"Haunted",
"Last Kiss",
"Long Live",
"Ours",
"If This Was A Movie",
"Superman",
"Back To December - Acoustic",
"Haunted - Acoustic Version",
"Mine",
"Back To December",
"The Story Of Us",
"State Of Grace",
"Red",
"Treacherous",
"I Knew You Were Trouble.",
"All Too Well",
"22",
"I Almost Do",
"We Are Never Ever Getting Back Together",
"Stay Stay Stay",
"The Last Time",
"Holy Ground",
"Sad Beautiful Tragic",
"The Lucky One",
"Everything Has Changed",
"Starlight",
"Begin Again",
"The Moment I Knew",
"Come Back...Be Here",
"Girl At Home",
"Treacherous - Original Demo Recording",
"Red - Original Demo Recording",
"State Of Grace - Acoustic",
"Welcome To New York",
"Blank Space",
"Style",
"Out Of The Woods",
"All You Had To Do Was Stay",
"Shake It Off",
"I Wish You Would",
"Bad Blood",
"Wildest Dreams",
"How You Get The Girl",
"This Love",
"I Know Places",
"Clean",
"Wonderland",
"You Are In Love",
"New Romantics",
"I Know Places - Voice Memo",
"I Wish You Would - Voice Memo",
"Blank Space - Voice Memo",
"...Ready For It?",
"End Game",
"I Did Something Bad",
"Don’t Blame Me",
"Delicate",
"Look What You Made Me Do",
"So It Goes...",
"Gorgeous",
"Getaway Car",
"King Of My Heart",
"Dancing With Our Hands Tied",
"Dress",
"This Is Why We Can't Have Nice Things",
"Call It What You Want",
"New Year’s Day",
"I Forgot That You Existed",
"Cruel Summer",
"Lover",
"The Man",
"The Archer",
"I Think He Knows",
"Miss Americana & The Heartbreak Prince",
"Paper Rings",
"Cornelia Street",
"Death By A Thousand Cuts",
"London Boy",
"Soon You’ll Get Better (feat. The Chicks)",
"False God",
"You Need To Calm Down",
"Afterglow",
"ME! (feat. Brendon Urie of Panic! At The Disco)",
"It’s Nice To Have A Friend",
"Daylight",
"the 1",
"cardigan",
"the last great american dynasty",
"exile (feat. Bon Iver)",
"my tears ricochet",
"mirrorball",
"seven",
"august",
"this is me trying",
"illicit affairs",
"invisible string",
"mad woman",
"epiphany",
"betty",
"peace",
"hoax",
"the lakes - bonus track",
"willow",
"champagne problems",
"gold rush",
"‘tis the damn season",
"tolerate it",
"no body",
"happiness",
"dorothea",
"coney island (feat. The National)",
"ivy",
"cowboy like me",
"long story short",
"marjorie",
"closure",
"evermore (feat. Bon Iver)",
"right where you left me - bonus track",
"it’s time to go - bonus track",
"Fearless (Taylor’s Version)",
"Fifteen (Taylor’s Version)",
"Love Story (Taylor’s Version)",
"Hey Stephen (Taylor’s Version)",
"White Horse (Taylor’s Version)",
"You Belong With Me (Taylor’s Version)",
"Breathe (feat. Colbie Caillat) (Taylor’s Version)",
"Tell Me Why (Taylor’s Version)",
"You’re Not Sorry (Taylor’s Version)",
"The Way I Loved You (Taylor’s Version)",
"Forever & Always (Taylor’s Version)",
"The Best Day (Taylor’s Version)",
"Change (Taylor’s Version)",
"Jump Then Fall (Taylor’s Version)",
"Untouchable (Taylor’s Version)",
"Forever & Always (Piano Version) (Taylor’s Version)",
"Come In With The Rain (Taylor’s Version)",
"Superstar (Taylor’s Version)",
"The Other Side Of The Door (Taylor’s Version)",
"Today Was A Fairytale (Taylor’s Version)",
"You All Over Me (feat. Maren Morris) (Taylor’s Version) (From The Vault)",
"Mr. Perfectly Fine (Taylor’s Version) (From The Vault)",
"We Were Happy (Taylor’s Version) (From The Vault)",
"That’s When (feat. Keith Urban) (Taylor’s Version) (From The Vault)",
"Don’t You (Taylor’s Version) (From The Vault)",
"Bye Bye Baby (Taylor’s Version) (From The Vault)",
];

function getSong() {
    let song = Math.floor(Math.random() * 171);
    document.getElementById("song_text").style.display = "block";
    document.getElementById("song").innerText = songs[song];
}